#google_analytics: UA-NNNNNNNN-N

title: "안녕하세요."
description: "최대한 많은 것을 기록하기 위한 블로그입니다."

url: "https://eabinn.github.io"

header_pages:
  - index.md
  - about.md

footer: Stay hungry. Stay foolish. - Steve Jobs

markdown: kramdown

comments:
  provider: "disqus"
  disqus:
    shortname: "eabinn-github-io"

plugins:
  - jekyll-seo-tag
