#google_analytics: UA-NNNNNNNN-N

title: "안녕하세요."
description: "최대한 많은 것을 기록하기 위한 블로그입니다."

url: "https://eabinn.github.io"

header_pages:
  - index.md
  - about.md

footer: Stay hungry. Stay foolish. - Steve Jobs

# markdown
markdown: kramdown

# comment
comments:
  provider: "utterances"

# plugins
plugins:
  - jekyll-seo-tag
